version: '3'

networks:
  app:
    driver: bridge

services:
  database:
    restart: unless-stopped
    image: postgres
    networks:
    - app
    env_file:
      - .env

  api:
    restart: unless-stopped
    image: api
    build:
      dockerfile: Dockerfile
      context: .
    networks:
    - app
    env_file:
      - .env
    volumes:
      - ./app:/opt/app/app
    ports:
      - "8000:8000"
    command: "uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload"
